// Starter projects for the gallery. Each one is a real multi-volume parametric
// composition — the same schema Claude produces — so opening one drops you
// straight into a rich model you can pull apart.
//
// Their napkin thumbnails are not drawings someone made: they are generated by
// projecting the actual massing into an axonometric line drawing and adding a
// hand's worth of wobble. Model and sketch can therefore never disagree.

export const EXAMPLES = [
  {
    id: 'torsion',
    name: 'Torsion Tower',
    type: 'office',
    archetype: 'tower',                 // the full CONCORD torso-tower model
    reading: 'a 90° twisting torso of nine stacked segments on an exposed spine',
    camera: { yawDeg: 32, pitchDeg: 12 },
    params: {
      floors: 45, floorHeight: 3.6, baseWidth: 34, baseDepth: 28,
      twist: 90, taper: 0.92, cornerRadius: 5, segCount: 9, spine: true,
      finSpacing: 2.4, liftGround: 0, podiumFloors: 0, podiumExpand: 0,
      facade: 'glass', structure: 'concrete', balconyDepth: 0, greenRoof: false,
      crown: 'flat', orientation: 0, setbacks: [], skyGardens: [22, 33],
    },
    // a stand-in massing purely for the gallery thumbnail
    masses: [
      { id: 's1', role: 'tower', w: 34, d: 28, h: 36, x: 0, y: 0, z: 0, rotY: 0, facade: 'glass' },
      { id: 's2', role: 'tower', w: 32, d: 26, h: 36, x: 0, y: 36, z: 0, rotY: 22, facade: 'glass' },
      { id: 's3', role: 'tower', w: 30, d: 24, h: 36, x: 0, y: 72, z: 0, rotY: 45, facade: 'glass' },
      { id: 's4', role: 'tower', w: 28, d: 23, h: 34, x: 0, y: 108, z: 0, rotY: 68, facade: 'glass' },
      { id: 's5', role: 'tower', w: 26, d: 21, h: 24, x: 0, y: 142, z: 0, rotY: 88, facade: 'glass' },
    ],
  },
  {
    id: 'delta',
    name: 'Delta Museum',
    type: 'museum',
    reading: 'a long gallery bar cantilevered over a glass hall and a public plinth',
    camera: { yawDeg: 34, pitchDeg: 11 },
    masses: [
      { id: 'plinth', role: 'podium', w: 46, d: 32, h: 6, x: 0, y: 0, z: 0, rotY: 0, facade: 'solid', on: 'ground' },
      { id: 'hall', role: 'volume', w: 28, d: 22, h: 15, x: -4, y: 6, z: 2, rotY: 0, facade: 'glass', on: 'plinth' },
      { id: 'bar', role: 'bar', w: 42, d: 13, h: 9, x: 9, y: 21, z: -3, rotY: 0, facade: 'slats-h', cantilever: true, on: 'hall' },
      { id: 'core', role: 'core', w: 9, d: 9, h: 27, x: -20, y: 6, z: -9, rotY: 0, facade: 'solid', on: 'plinth' },
      { id: 'canopy', role: 'canopy', w: 18, d: 8, h: 1.2, x: 6, y: 6.5, z: 17, rotY: 0, facade: 'solid' },
    ],
  },
  {
    id: 'terraces',
    name: 'Stepped Terraces',
    type: 'residential',
    reading: 'housing stepping back floor by floor so every flat keeps a terrace',
    camera: { yawDeg: 24, pitchDeg: 12 },
    masses: [
      { id: 'street', role: 'podium', w: 42, d: 20, h: 7, x: 0, y: 0, z: 0, rotY: 0, facade: 'glass', on: 'ground' },
      { id: 't1', role: 'volume', w: 38, d: 17, h: 7, x: 0, y: 7, z: -1.5, rotY: 0, facade: 'solid', on: 'street' },
      { id: 't2', role: 'volume', w: 33, d: 15, h: 7, x: 0, y: 14, z: -2.5, rotY: 0, facade: 'solid', on: 't1' },
      { id: 't3', role: 'volume', w: 27, d: 13, h: 7, x: 0, y: 21, z: -3.5, rotY: 0, facade: 'solid', on: 't2' },
      { id: 't4', role: 'volume', w: 20, d: 11, h: 7, x: 0, y: 28, z: -4.5, rotY: 0, facade: 'slats-h', on: 't3' },
      { id: 'stair', role: 'core', w: 6, d: 6, h: 36, x: -22, y: 0, z: 0, rotY: 0, facade: 'solid', on: 'ground' },
    ],
  },
  {
    id: 'courtyard',
    name: 'Courtyard Labs',
    type: 'laboratory',
    reading: 'three research bars around a court, linked by a glazed bridge',
    camera: { yawDeg: 38, pitchDeg: 20 },
    masses: [
      { id: 'north', role: 'bar', w: 48, d: 13, h: 22, x: 0, y: 0, z: -17, rotY: 0, facade: 'slats-v', on: 'ground' },
      { id: 'south', role: 'bar', w: 48, d: 13, h: 18, x: 0, y: 0, z: 17, rotY: 0, facade: 'slats-v', on: 'ground' },
      { id: 'west', role: 'bar', w: 13, d: 22, h: 22, x: -18, y: 0, z: 0, rotY: 0, facade: 'solid', on: 'ground' },
      { id: 'bridge', role: 'volume', w: 11, d: 34, h: 4.5, x: 14, y: 13, z: 0, rotY: 0, facade: 'glass', cantilever: true },
      { id: 'plant', role: 'volume', w: 16, d: 10, h: 5, x: 12, y: 22, z: -17, rotY: 0, facade: 'slats-h', on: 'north' },
    ],
  },
  {
    id: 'harbor',
    name: 'Harbor Hotel',
    type: 'hotel',
    reading: 'a thin room slab riding a public podium, pool box on the roof',
    camera: { yawDeg: 20, pitchDeg: 10 },
    masses: [
      { id: 'podium', role: 'podium', w: 40, d: 28, h: 8, x: 0, y: 0, z: 0, rotY: 0, facade: 'glass', on: 'ground' },
      { id: 'slab', role: 'bar', w: 36, d: 14, h: 44, x: -1, y: 8, z: -4, rotY: 6, facade: 'slats-h', on: 'podium' },
      { id: 'pool', role: 'volume', w: 21, d: 12, h: 4.5, x: -1, y: 52, z: -4, rotY: 6, facade: 'glass', on: 'slab' },
      { id: 'wing', role: 'wing', w: 15, d: 12, h: 12, x: 20, y: 0, z: 12, rotY: -12, facade: 'solid', on: 'ground' },
    ],
  },
];

// ---------- massing -> hand-drawn axonometric strokes ----------

const ISO = Math.PI / 6;           // 30° axonometric
function project(x, y, z) {
  return {
    x: (x - z) * Math.cos(ISO),
    y: y * 0.92 - (x + z) * Math.sin(ISO) * 0.55,
  };
}

function corners(m) {
  const hw = m.w / 2, hd = m.d / 2;
  const r = (m.rotY || 0) * Math.PI / 180;
  const cs = Math.cos(r), sn = Math.sin(r);
  const out = [];
  for (const sy of [0, 1]) {
    for (const [sx, sz] of [[-1, -1], [1, -1], [1, 1], [-1, 1]]) {
      const lx = sx * hw, lz = sz * hd;
      out.push({
        x: m.x + lx * cs - lz * sn,
        y: m.y + sy * m.h,
        z: m.z + lx * sn + lz * cs,
      });
    }
  }
  return out; // 0-3 bottom, 4-7 top
}

// Corner indices: 0-3 bottom (−x−z, +x−z, +x+z, −x+z), 4-7 the same on top.
// Seen from the front-top-right only three faces face us. A hand draws those
// nine edges and nothing else — drawing all twelve is what makes a sketch look
// like an X-ray wireframe instead of a building.
const VISIBLE_FACES = {
  top: [4, 5, 6, 7],
  front: [3, 2, 6, 7],   // +z face, toward the viewer
  right: [2, 1, 5, 6],   // +x face
};
const VISIBLE_EDGES = [
  [4, 5], [5, 6], [6, 7], [7, 4],   // top outline
  [3, 2], [2, 1],                    // ground edges of the two seen walls
  [3, 7], [2, 6], [1, 5],            // the three seen verticals
];

function wobble(seed) {
  const s = Math.sin(seed * 127.1) * 43758.5453;
  return (s - Math.floor(s)) - 0.5;
}

export function strokesFor(masses, { jitter = 1 } = {}) {
  const segs = [];
  masses.forEach((m, mi) => {
    const c = corners(m).map(p => project(p.x, p.y, p.z));
    VISIBLE_EDGES.forEach(([a, b], ei) => segs.push({ a: c[a], b: c[b], seed: mi * 31 + ei }));
  });
  if (!segs.length) return [];

  let minX = 1e9, maxX = -1e9, minY = 1e9, maxY = -1e9;
  for (const s of segs) for (const p of [s.a, s.b]) {
    minX = Math.min(minX, p.x); maxX = Math.max(maxX, p.x);
    minY = Math.min(minY, p.y); maxY = Math.max(maxY, p.y);
  }
  const span = Math.max(maxX - minX, maxY - minY) || 1;
  const pad = 0.13;
  const sc = (1 - pad * 2) / span;
  const offX = pad + ((1 - pad * 2) - (maxX - minX) * sc) / 2;
  const offY = pad + ((1 - pad * 2) - (maxY - minY) * sc) / 2;
  const map = p => ({
    x: offX + (p.x - minX) * sc,
    y: 1 - (offY + (p.y - minY) * sc),   // screen y grows downward
  });

  // each edge becomes a short 4-point polyline with a little overshoot
  const strokes = segs.map(s => {
    const A = map(s.a), B = map(s.b);
    const dx = B.x - A.x, dy = B.y - A.y;
    const over = 0.012 * jitter;
    const pts = [];
    for (let i = 0; i <= 3; i++) {
      const t = -over + (i / 3) * (1 + over * 2);
      pts.push({
        x: A.x + dx * t + wobble(s.seed + i * 2.1) * 0.006 * jitter,
        y: A.y + dy * t + wobble(s.seed + i * 5.7) * 0.006 * jitter,
      });
    }
    return { tool: 'pen', pts };
  });

  // ground line, drawn last like an architect would
  const groundY = 1 - (offY + (0 - minY) * sc);
  strokes.push({
    tool: 'pen',
    pts: [
      { x: 0.06, y: groundY + 0.012 + wobble(99) * 0.004 },
      { x: 0.45, y: groundY + 0.014 + wobble(98) * 0.004 },
      { x: 0.94, y: groundY + 0.010 + wobble(97) * 0.004 },
    ],
  });
  return strokes;
}

// Gallery thumbnail: a proper pencil axonometric. Volumes are painted back to
// front with paper-coloured faces, so nearer boxes genuinely hide the ones
// behind them (a wireframe cannot do this), then the seen edges are drawn over
// the top and the side wall gets a little hatching for weight.
export function thumbSVG(masses, stroke = '#4a4a52') {
  if (!masses?.length) return '';
  const boxes = masses.map((m, i) => ({ m, i, c: corners(m).map(p => project(p.x, p.y, p.z)) }));

  let minX = 1e9, maxX = -1e9, minY = 1e9, maxY = -1e9;
  for (const b of boxes) for (const p of b.c) {
    minX = Math.min(minX, p.x); maxX = Math.max(maxX, p.x);
    minY = Math.min(minY, p.y); maxY = Math.max(maxY, p.y);
  }
  const span = Math.max(maxX - minX, maxY - minY) || 1;
  const pad = 12, size = 100 - pad * 2;
  const sc = size / span;
  const ox = pad + (size - (maxX - minX) * sc) / 2;
  const oy = pad + (size - (maxY - minY) * sc) / 2;
  const P = p => [ox + (p.x - minX) * sc, 100 - (oy + (p.y - minY) * sc)];
  const jit = (v, seed, amt = 0.5) => v + wobble(seed) * amt;

  // painter's order: things further from the viewer first
  boxes.sort((a, b) => (a.m.x + a.m.z + a.m.y * 0.35) - (b.m.x + b.m.z + b.m.y * 0.35));

  let out = '';
  for (const b of boxes) {
    const poly = idx => idx.map((k, n) => {
      const [x, y] = P(b.c[k]);
      return `${jit(x, b.i * 17 + k + n, 0.45).toFixed(1)},${jit(y, b.i * 23 + k, 0.45).toFixed(1)}`;
    }).join(' ');
    // opaque faces = occlusion
    out += `<polygon points="${poly(VISIBLE_FACES.top)}" fill="#faf7ee"/>`;
    out += `<polygon points="${poly(VISIBLE_FACES.front)}" fill="#f4efe2"/>`;
    out += `<polygon points="${poly(VISIBLE_FACES.right)}" fill="#eae4d3"/>`;
    // hatch the darker right-hand wall, the way you would with a pencil
    const [rx0, ry0] = P(b.c[2]), [rx1, ry1] = P(b.c[1]), [rx2, ry2] = P(b.c[5]);
    const steps = Math.max(2, Math.min(9, Math.round(Math.hypot(rx1 - rx0, ry1 - ry0) / 2.6)));
    for (let s = 1; s < steps; s++) {
      const t = s / steps;
      const ax = rx0 + (rx1 - rx0) * t, ay = ry0 + (ry1 - ry0) * t;
      const bx = ax + (rx2 - rx1), by = ay + (ry2 - ry1);
      out += `<line x1="${ax.toFixed(1)}" y1="${ay.toFixed(1)}" x2="${jit(bx, s + b.i, 0.6).toFixed(1)}" y2="${by.toFixed(1)}" stroke="${stroke}" stroke-width="0.35" opacity="0.28"/>`;
    }
    // then the drawn lines, doubled slightly for a graphite feel
    for (const [a, c] of VISIBLE_EDGES) {
      const [x1, y1] = P(b.c[a]), [x2, y2] = P(b.c[c]);
      const ox1 = jit(x1, b.i + a, 0.5), oy1 = jit(y1, b.i + a * 2, 0.5);
      const ox2 = jit(x2, b.i + c, 0.5), oy2 = jit(y2, b.i + c * 3, 0.5);
      const dx = (ox2 - ox1) * 0.05, dy = (oy2 - oy1) * 0.05;   // overshoot
      out += `<line x1="${(ox1 - dx).toFixed(1)}" y1="${(oy1 - dy).toFixed(1)}" x2="${(ox2 + dx).toFixed(1)}" y2="${(oy2 + dy).toFixed(1)}" stroke="${stroke}" stroke-width="0.85" opacity="0.85"/>`;
      out += `<line x1="${ox1.toFixed(1)}" y1="${(oy1 + 0.35).toFixed(1)}" x2="${ox2.toFixed(1)}" y2="${(oy2 + 0.35).toFixed(1)}" stroke="${stroke}" stroke-width="0.4" opacity="0.3"/>`;
    }
  }
  // ground line
  const gy = 100 - (oy + (0 - minY) * sc);
  out += `<line x1="6" y1="${(gy + 1).toFixed(1)}" x2="94" y2="${(gy + 0.4).toFixed(1)}" stroke="${stroke}" stroke-width="0.6" opacity="0.45"/>`;

  return `<svg viewBox="0 0 100 100" preserveAspectRatio="xMidYMid meet" aria-hidden="true">
    <g stroke-linecap="round" stroke-linejoin="round">${out}</g></svg>`;
}
